name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: PYTHONPATH=. pytest --maxfail=1 --disable-warnings -q

  build-and-deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: gcr.io/${{ secrets.GCP_PROJECT }}/cafe-agent:latest
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cafe-agent
          image: gcr.io/${{ secrets.GCP_PROJECT }}/cafe-agent:latest