name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set dummy env vars for tests
        run: |
          echo "GCP_PROJECT=test-project"           >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=test-token"          >> $GITHUB_ENV
          echo "GOOGLE_SHEET_ID=test-sheet-id"      >> $GITHUB_ENV
          echo "GEMINI_API_KEY=test-key"            >> $GITHUB_ENV

      - name: Run tests
        run: PYTHONPATH=. pytest --maxfail=1 --disable-warnings -q

  build-and-deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cafe-agent-repo/cafe-agent:latest


      # Now deploy with the official action:
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cafe-agent
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cafe-agent-repo/cafe-agent:latest
          region: ${{ secrets.GCP_REGION }}
          service_account: ${{ secrets.CLOUD_RUN_SA_EMAIL }}
          # mount your SA JSON into /tmp/sa.json
          secrets: |
            /tmp/sa.json=cafe-agent-sa:latest
          # now your app can see GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa.json
          env_vars: |
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            GCP_PROJECT=${{ secrets.GCP_PROJECT }}
            GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa.json
