name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: PYTHONPATH=. pytest --maxfail=1 --disable-warnings -q

  build-and-deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Write service account to file
        run: echo '${{ secrets.GCP_SA_KEY }}' > sa.json

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cafe-agent-repo/cafe-agent:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cafe-agent
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cafe-agent-repo/cafe-agent:latest
          region: ${{ secrets.GCP_REGION }}
          env_vars: |
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            GCP_PROJECT=${{ secrets.GCP_PROJECT }}
            GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa.json
