name: CI/CD
on:
  push:
    branches: [ main ]
    
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Set dummy env for tests
        run: |
          echo "GCP_PROJECT=test-project" >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=test-token" >> $GITHUB_ENV
          echo "GOOGLE_SHEET_ID=test-sheet-id" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=test-key" >> $GITHUB_ENV
      - run: PYTHONPATH=. pytest --maxfail=1 -q

  build-and-deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cafe-agent-repo/cafe-agent:latest

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cafe-agent
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cafe-agent-repo/cafe-agent:latest
          region: ${{ secrets.GCP_REGION }}
          service_account: github-deployer@cafe-agent-app.iam.gserviceaccount.com
          env_vars: |
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            GCP_PROJECT=${{ secrets.GCP_PROJECT }}
