name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set dummy env vars for tests
        run: |
          echo "GCP_PROJECT=test-project" >> $GITHUB_ENV
          echo "TELEGRAM_TOKEN=test-token" >> $GITHUB_ENV
          echo "GOOGLE_SHEET_ID=test-sheet-id" >> $GITHUB_ENV
          echo "GOOGLE_APPLICATION_CREDENTIALS=test.json" >> $GITHUB_ENV
          echo "GEMINI_API_KEY=test-key" >> $GITHUB_ENV

      - name: Run tests
        run: PYTHONPATH=. pytest --maxfail=1 --disable-warnings -q

  build-and-deploy:
    needs: lint-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure Docker
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build & Push Docker image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cafe-agent-repo/cafe-agent:latest

      - name: Create /tmp/sa.json from base64 secret
        run: echo "$GCP_SA_KEY_BASE64" | base64 -d > /tmp/sa.json
        env:
          GCP_SA_KEY_BASE64: ${{ secrets.GCP_SA_KEY_BASE64 }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: cafe-agent
          image: us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/cafe-agent-repo/cafe-agent:latest
          region: ${{ secrets.GCP_REGION }}
          env_vars: |
            TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
            GOOGLE_SHEET_ID=${{ secrets.GOOGLE_SHEET_ID }}
            GEMINI_API_KEY=${{ secrets.GEMINI_API_KEY }}
            GCP_PROJECT=${{ secrets.GCP_PROJECT }}
            GOOGLE_APPLICATION_CREDENTIALS=/tmp/sa.json
